project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: docs/links/index.qmd
        text: Links
    right:
      - icon: twitter
        href: https://twitter.com/kowandtoilet
        aria-label: Twitter
  page-footer:
    right:
      - icon: twitter
        href: https://twitter.com/kowandtoilet

format:
  html:
    theme:
      light: [vapor]
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
